CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_digest TEXT NOT NULL,
    nickname VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS COMMNETS (
    id SERIAL PRIMARY KEY,
    uploader VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL
);